/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  videoCalling: [{ type: 'autogenerated', dirName: 'video-calling' }],
  voiceCalling: [{ type: 'autogenerated', dirName: 'voice-calling' }],
  realtimeMessaging: [{ type: 'autogenerated', dirName: 'realtime-messaging' }]
};

module.exports = sidebars;
