/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  docSidebar: [{ type: 'autogenerated', dirName: './video-calling' }]
};

module.exports = sidebars;
